//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harvester.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Harvester.Core.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended property not defined.
        ///Property: {0}.
        /// </summary>
        public static string ExtendedPropertyNotDefined {
            get {
                return ResourceManager.GetString("ExtendedPropertyNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute must be a valid pipe name.
        ///Example: \\.\pipe\Harvester.
        /// </summary>
        public static string InvalidNamedPipeBinding {
            get {
                return ResourceManager.GetString("InvalidNamedPipeBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute must be a unique mutex name.
        ///Example: HarvesterMutex.
        /// </summary>
        public static string InvalidNamedPipeMutex {
            get {
                return ResourceManager.GetString("InvalidNamedPipeMutex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute must be a valid memory mapped file name.
        ///Example: Local\HRVSTWIN.
        /// </summary>
        public static string InvalidSharedMemoryBinding {
            get {
                return ResourceManager.GetString("InvalidSharedMemoryBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute must be a unique mutex name.
        ///Example: HrvstWinMutex.
        /// </summary>
        public static string InvalidSharedMemoryMutex {
            get {
                return ResourceManager.GetString("InvalidSharedMemoryMutex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot combine OutputDebugString messages originating from different processes..
        /// </summary>
        public static string OutputDebugStringProcessMismatch {
            get {
                return ResourceManager.GetString("OutputDebugStringProcessMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than zero..
        /// </summary>
        public static string ValueGreaterThanZeroExpected {
            get {
                return ResourceManager.GetString("ValueGreaterThanZeroExpected", resourceCulture);
            }
        }
    }
}
