//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harvester.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Harvester.Core.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown buffer type specified &apos;{0}&apos;; supported buffer types are &apos;SharedMemoryBuffer&apos; and &apos;NamedPipeBuffer&apos;.
        /// </summary>
        public static string BufferTypeNotSupported {
            get {
                return ResourceManager.GetString("BufferTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of Harvester is already open..
        /// </summary>
        public static string DebuggerAlreadyActive {
            get {
                return ResourceManager.GetString("DebuggerAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended property not defined.
        ///Property: {0}.
        /// </summary>
        public static string ExtendedPropertyNotDefined {
            get {
                return ResourceManager.GetString("ExtendedPropertyNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown filter type.
        ///Friendly Name:{0}.
        /// </summary>
        public static string FilterTypeNotKnown {
            get {
                return ResourceManager.GetString("FilterTypeNotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid NamedPipe name.
        ///Example: \\.\pipe\CustomPipeName.
        /// </summary>
        public static string InvalidNamedPipeName {
            get {
                return ResourceManager.GetString("InvalidNamedPipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SharedMemoryBuffer name.
        ///Example: Local\CustomBufferName.
        /// </summary>
        public static string InvalidSharedMemoryBufferName {
            get {
                return ResourceManager.GetString("InvalidSharedMemoryBufferName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying message buffer is broken..
        /// </summary>
        public static string MessageBufferBroken {
            get {
                return ResourceManager.GetString("MessageBufferBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying message buffer is closed..
        /// </summary>
        public static string MessageBufferClosed {
            get {
                return ResourceManager.GetString("MessageBufferClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching system events found..
        /// </summary>
        public static string NoMatchesFound {
            get {
                return ResourceManager.GetString("NoMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot combine OutputDebugString messages originating from different processes..
        /// </summary>
        public static string OutputDebugStringProcessMismatch {
            get {
                return ResourceManager.GetString("OutputDebugStringProcessMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit application....
        /// </summary>
        public static string PressAnyKeyToExit {
            get {
                return ResourceManager.GetString("PressAnyKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than zero..
        /// </summary>
        public static string ValueGreaterThanZeroExpected {
            get {
                return ResourceManager.GetString("ValueGreaterThanZeroExpected", resourceCulture);
            }
        }
    }
}
